pos/channels/urls.py
from django.urls import path
from . import views


app_name = 'channels'


urlpatterns = [
    path('channel_list/', views.channel_list_on_server, name='channel_list'),
    path('return_json_value/<str:AppId>/', views.return_json_value, name='return_json_value'),
    path('show_details/<str:AppId>/<str:AppName>/', views.ShowDetailsOfChannelView.as_view(), 
        name='show_details'),
    path('downloads/', views.DownloadAndSaveView.as_view(), name='downloads'),
    path('json_data/<str:id>/', views.json_data_storage_view, name='json_data'),
    path('no_internet/', views.NoInternetView.as_view(), name='no_internet'),
]

pos/pos/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('register/', include('account.urls')),
    path('channel/', include('channels.urls')),
    path('content/', include('content_viewer.urls')),
    path('push/', include('push.urls')),
    path('api/', include('core_api.urls')),
    path('api/channel/', include('channels_api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/channels/models.py
from django.db import models
from jsonfield import JSONField


# fetching data from "http://devposapi.prathamopenschool.org/api/AppList" url
class AppListFromServerData(models.Model):
    AppId = models.CharField(max_length=30, primary_key=True)
    AppName = models.CharField(max_length=100)
    ThumbUrl = models.URLField(max_length=700)
    AppDesc = models.TextField(blank=True, null=True)
    AppOrder = models.CharField(max_length=20, default='')
    DateUpdated = models.CharField(max_length=100, default='',
                                   null=True, blank=True)
    fileName = models.CharField(max_length=100, default='', null=True,
                                blank=True)
    localUrl = models.CharField(max_length=100, default='', null=True,
                                blank=True)

    @classmethod
    def create(cls, AppId, AppName, ThumbUrl, AppDesc, AppOrder, DateUpdated):
        applist_server_data = cls(AppId=AppId, AppName=AppName, ThumbUrl=ThumbUrl,
                                  AppDesc=AppDesc, AppOrder=AppOrder,
                                  DateUpdated=DateUpdated, fileName=fileName,
                                  localUrl=localUrl)

        return applist_server_data

    def __str__(self):
        return self.AppId


# filling local db of project from http://devposapi.prathamopenschool.org/Api/AppNodeDetailListByNode?id=<ids>
# at http://localhost:8000/channel/app_available/
class AppAvailableInDB(models.Model):
    applistfromserverdata = models.ForeignKey(AppListFromServerData, on_delete=models.CASCADE)
    NodeId = models.CharField(max_length=100, default='')
    NodeType = models.CharField(max_length=100, default='')
    NodeTitle = models.CharField(max_length=100, default='')
    JsonData = JSONField(default={}, blank=True)
    ParentId = models.CharField(max_length=100, blank=True, null=True)
    AppId = models.CharField(max_length=100, default='')
    DateUpdated = models.CharField(max_length=100, default='',
                                   null=True, blank=True)

    @classmethod
    def create(cls, NodeId, NodeType, NodeTitle, JsonData, ParentId, AppId, DateUpdated):
        app_data = cls(NodeId=NodeId, NodeType=NodeType, NodeTitle=NodeTitle, JsonData=JsonData,
                       ParentId=ParentId, AppId=AppId, DateUpdated=DateUpdated)
        return app_data

    def __str__(self):
        return self.NodeId


# filling the data of lstfiles from http://devposapi.prathamopenschool.org/Api/AppNodeDetailListByNode?id=<ids>
class FileDataToBeStored(models.Model):
    appavailableindb = models.ForeignKey(AppAvailableInDB, related_name='LstFileList', on_delete=models.CASCADE)
    FileId = models.IntegerField()
    NodeId = models.CharField(max_length=100)
    FileType = models.CharField(max_length=100)
    FileUrl = models.URLField(max_length=500)
    DateUpdated = models.CharField(
        max_length=100, null=True, blank=True, default='')
    fileName = models.CharField(max_length=100, default='', null=True,
                                blank=True)
    localUrl = models.CharField(max_length=100, default='', null=True,
                                blank=True)

    @classmethod
    def create(cls, FileId, NodeId, FileType, FileUrl, DateUpdated):
        file_data = cls(FileId=FileId, NodeId=NodeId, FileType=FileType, FileUrl=FileUrl,
                        DateUpdated=DateUpdated, fileName=fileName, localUrl=localUrl)

        return file_data

    def __str__(self):
        return str(self.FileId)

    # @property
    # def imageURL(self):
    #     try:
    #         url = self.localUrl
    #     except:
    #         url = ''
    #     return url


class FileUpload(models.Model):
    uploaded_file = models.FileField(upload_to='media/')


class JsonDataStorage(models.Model):
    JsonId      =     models.CharField(max_length=50, default='')
    NodeId      =     models.CharField(max_length=50, default='')
    JsonType    =     models.CharField(max_length=50, default='') 
    JsonData    =     JSONField(default={}, blank=True)
    DateUpdated =     models.CharField(max_length=100, default='',
                                   null=True, blank=True)

    @classmethod
    def create(cls, JsonId, NodeId, JsonType, JsonData, DateUpdated):
        json_data_storage = cls(JsonId=JsonId, NodeId=NodeId, JsonType=JsonType, JsonData=JsonData,
                       DateUpdated=DateUpdated)
        return json_data_storage

    def __str__(self):
        return self.JsonId

pos/channels/views.py
import os
import json
import time
import requests
from pathlib import Path
# from pprint import pprint
from django.shortcuts import render
# from django.views.generic.edit import CreateView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import View, TemplateView, ListView
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import (AppAvailableInDB, AppListFromServerData,
                     FileDataToBeStored, JsonDataStorage)

# rest framework imports
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view

# command line progress bar import
from clint.textui import progress

#custom imports
from channels.file_downloader import Downloader

# creating object of Downloader class
downloading = Downloader()


# home directory check for every os
homeDir = str(Path.home())

# headers for data fetching
headers = {
    'cache-control': "no-cache",
    'content-type': "application/json; charset=utf-8",
    "Accept": "application/json"
}

channels_result = None

# getting list of channels using API
@login_required
def channel_list_on_server(request):
    # global channels_result
    try:
        context = {}
        channels_url = "http://devposapi.prathamopenschool.org/api/AppList"
        channels_response = requests.get(channels_url, headers=headers)
        channels_result = json.loads(channels_response.content.decode("utf-8"))
        for app in  channels_result:
            for k,v in app.items():
                if k == 'AppName':
                    downloading.download_files_without_qs(channels_url, v)
        context['channels_from_server'] = channels_result
        return render(request, 'channels/channels_list_from_server.html', context=context)
    except requests.exceptions.ConnectionError:
        return HttpResponseRedirect('/channel/no_internet/')


# return the json response in api form for showing checkboxes nad details
@api_view(['GET'])
def return_json_value(request, AppId):
    try:
        url_to_convert = "http://devposapi.prathamopenschool.org/api/AppNode?id={}" .format(
            AppId)
        response_url = requests.get(url_to_convert, headers=headers)
        result_url = json.loads(response_url.content.decode('utf-8'))
        context = {
            'json_data': result_url,
        }
        return Response(context, status=status.HTTP_200_OK)
    except requests.exceptions.ConnectionError:
        return HttpResponseRedirect('/channel/no_internet/')


# showing the page to downlaod the content (jsondata and files)
class ShowDetailsOfChannelView(LoginRequiredMixin, View):
    template_name = "channels/show_details.html"

    def get(self, request, AppId, AppName, *args, **kwargs):
        try:
            context = {}
            print('AppId ', AppId, AppName)
            context['AppId'] = AppId
            context['AppName'] = AppName
            return render(self.request, self.template_name, context=context)
        except requests.exceptions.ConnectionError:
            return HttpResponseRedirect('/channel/no_internet/')


# Downloading and saving the jsondata and files with ids
class DownloadAndSaveView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        node_values = request.POST.getlist('node_values[]')
        AppId = request.POST.get('AppId')
        AppName = request.POST.get('AppName')

        channels_url = "http://devposapi.prathamopenschool.org/api/AppList"
        channels_response = requests.get(channels_url, headers=headers)
        channels_result = json.loads(channels_response.content.decode("utf-8"))

        """ downloading and saving the content from here
            looping through node_values list"""
        # applist_server_data = None
        if not AppListFromServerData.objects.filter(AppId=AppId).exists():
            print(AppId, "server data not in db")
            for apps in channels_result:
                if apps["AppId"] == AppId:
                    applist_local_url = downloading.localUrl
                    applist_local_url = applist_local_url.split('static')[1]
                    # print("local url is ", 'static'+local_url)
                    applist_local_url = 'static'+applist_local_url
                    AppId = apps["AppId"]
                    AppName = apps['AppName']
                    ThumbUrl = apps['ThumbUrl']
                    AppDesc = apps['AppDesc']
                    AppOrder = apps['AppOrder']
                    DateUpdated = apps['DateUpdated']
                    fileName = os.path.basename(ThumbUrl)
                    localUrl = applist_local_url
                    # print("filename", fileName)
                    applist_server_data = AppListFromServerData.objects.create(AppId=AppId, AppName=AppName,
                                                                               ThumbUrl=ThumbUrl, AppDesc=AppDesc,
                                                                               AppOrder=AppOrder, DateUpdated=DateUpdated,
                                                                               fileName=fileName,
                                                                               localUrl=applist_local_url)
                    applist_server_data.save()
        else:
            # just pass the instance of existing app with app id
            applist_server_data = AppListFromServerData.objects.only(
                'AppId').get(AppId=AppId)

        for ids in node_values:
            # hit the detail node each time and get the result
            try:
                detail_node_url = "http://devposapi.prathamopenschool.org/Api/AppNodeDetailListByNode?id={}" .format(
                    ids)
                detail_node_response = requests.get(
                    detail_node_url, headers=headers, timeout=13)
                detail_node_json_val = json.loads(
                    detail_node_response.content.decode('utf-8'))

                # downloading the files
                response_data = downloading.download_files_with_qs(detail_node_url, {"id": ids}, AppName)

                if response_data is False:
                    return HttpResponseRedirect('/channel/no_internet/')
                else:
                    # print("localUrl is ", downloading.localUrl)
                    local_url = downloading.localUrl
                    local_url = local_url.split('static')[1]
                    # print("local url is ", 'static'+local_url)
                    local_url = 'static'+local_url
                    for detail in detail_node_json_val:
                        try:
                            NodeId = detail['NodeId']
                            NodeType = detail['NodeType']
                            NodeTitle = detail['NodeTitle']
                            JsonData = detail['JsonData']
                            ParentId = detail['ParentId']
                            AppId = detail['AppId']
                            DateUpdated = detail['DateUpdated']
                            if not AppAvailableInDB.objects.filter(NodeId=NodeId).exists():
                                app_in_db = AppAvailableInDB.objects.create(applistfromserverdata=applist_server_data,
                                                                            NodeId=NodeId, NodeType=NodeType, NodeTitle=NodeTitle,
                                                                            JsonData=JsonData, ParentId=ParentId,  AppId=AppId,
                                                                            DateUpdated=DateUpdated)
                                app_in_db.save()
                                for file in detail["LstFileList"]:
                                    print("file data is ", file)
                                    FileId = file['FileId']
                                    NodeId = file['NodeId']
                                    FileType = file['FileType']
                                    FileUrl = file['FileUrl']
                                    DateUpdated = file['DateUpdated']
                                    fileName = os.path.basename(FileUrl)
                                    localUrl = local_url
                                    if not FileDataToBeStored.objects.filter(NodeId=NodeId, FileId=FileId).exists():
                                        file_in_db = FileDataToBeStored.objects.create(appavailableindb=app_in_db,
                                                                                        FileId=FileId, NodeId=NodeId,
                                                                                        FileType=FileType, FileUrl=FileUrl,
                                                                                        DateUpdated=DateUpdated, 
                                                                                        fileName=fileName,
                                                                                        localUrl=local_url)
                                        file_in_db.save()

                        except requests.exceptions.ConnectionError:
                            print("db error")
                            return HttpResponseRedirect('/channel/no_internet/')
                
                json_data_storage_view(request, ids)

            except requests.exceptions.ConnectionError:
                print("downlaod error ")
                return HttpResponseRedirect('/channel/no_internet/')

        # return HttpResponse("success!!")
        print("successfully saved!")

pos/channels/templates/channels/channels_list_from_server.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/channels.css' %}">
{% block content %}
<br>
    {% if channels_from_server %}
        <main role="main">

      <section class="text-center">
        <div class="container">
          <h3 class="jumbotron-heading">Available content to download</h3>
        </div>
      </section>
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
          {% for apps in channels_from_server %}
              <div class="col-md-4">
                <div class="card mb-4 box-shadow" style="width: 14rem;">
                  <img class="card-img-top" src="{% static 'images/newlogo.jpg' %}"
                      width="50%" height="120" alt="Pratham Open School">
                  <div class="card-body">
                    <p class="card-text" style="font-size:medium;">
                    {{ apps.AppDesc }}</br></br>
                        <a href="{% url 'channels:show_details' AppId=apps.AppId AppName=apps.AppName %}">
                          <button type="button" class="btn btn-md btn-outline-success float-right">{{ apps.AppName }}</button>
                        </a>
                    </p>                    
                  </div>
                </div>
              </div>
          {% endfor %}
          </div>
        </div>
      </div>

    </main>
    {% else %}
        <p>no channels exists. Please Check the internet connection..!</p>   
    {% endif %}
{% endblock  %}

pos/channels/templates/channels/no_internet.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h3 class="display4 text-center">Sorry!! Internet Connection Is Not There</h3>
        </div>
    </div>
{% endblock %}

pos/channels/templates/channels/show_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <br>
    <div class="container">
        <p> Select content from {{ AppName }} </p>
        <div class="">
            <div class="breadcrumb">
                <div class="items">
                </div>
                <div class="btn-block pull-right">
                    <button type="submit" id="sort_ids" class="btn btn-success float-right" disabled>Download</button>
                    <div class="loading" id="loaded" style="display:none;">
                <div class="loader">
                <button class="btn btn-primary float-right" disabled>
                        <span class="spinner-grow spinner-grow-sm"></span>
                        Loading..
                      </button>
                </div>
                
                
            </div>
                </div>
            </div>
            <div id="dvtree">
            </div>
            
        </div>
    </div>
    <br><br/>
    <br><br/>

<script>
    let treeData = '';
    let uniqueArray = [];
    let res = "{{AppId}}";
    let AppName = "{{ AppName }}"
    $.ajax({
        url: '/channel/return_json_value/'+res+'/',
        type: 'GET',
        crossDomain: true,
        datatype: "jsonp",
        success: function(data) {
            treeData = data.json_data;
            createTree();
    }

});

    
function createTree(){
    let str = '';
    str=str+'<ul>';
    for (let i = 0; i < treeData.length; i++) {
        if(treeData[i]["ParentId"] === null){
            if(treeData[i].checked){
                str=str+'<li>\
            <a href="#" style="color:black;"\
             onclick="populateTree(\''+treeData[i]["NodeId"].toString()+'\');">'+treeData[i]["NodeTitle"]+'</a></li>';
            }
            else{
                str=str+'<li>\
            <a href="#" style="color:black;"\
             onclick="populateTree(\''+treeData[i]["NodeId"].toString()+'\');">'+treeData[i]["NodeTitle"]+'</a></li>';
            }
        }
    }

    str=str+'</ul>';
    $("#dvtree").html(str);

    }


function populateTree(parentid)
{
    let str = '';
    str=str+'<ul>';

    for (let i = 0; i < treeData.length; i++) {
        if(treeData[i]["ParentId"] !== null)
        {
        if(treeData[i]["ParentId"].toString() === parentid.toString())
        {
            if(treeData[i].checked){
                str=str+'<li>\
            <input type="checkbox" class="box" id="'+treeData[i]["NodeId"].toString()+'"\
            checked="true" onchange="indeterminateCall(this);" onclick="popup(this);">\
            <a href="#" style="color:black;"\
             onclick="populateTree(\''+treeData[i]["NodeId"].toString()+'\');">'+treeData[i]["NodeTitle"]+'</a></li>';
            }
            else{
                str=str+'<li>\
            <input type="checkbox" class="box" id="'+treeData[i]["NodeId"].toString()+'"\
            onchange="indeterminateCall(this);" onclick="popup(this);">\
            <a href="#" style="color:black;"\
             onclick="populateTree(\''+treeData[i]["NodeId"].toString()+'\');">'+treeData[i]["NodeTitle"]+'</a></li>';
            }
         }

        }
    }

    str=str+'</ul>';
    $("#dvtree").html(str);
     $(".items").empty();
    GetCrumb(parentid);
}

    function popup(id){
       if($(id).is(":checked")){
            var txt = document.getElementById(id.id);
            if (confirm("Do you really want all the content? It will take time .")) {
                //alert("You selected all. Please wait!!");
            } else {
                populateTree(id.id);
            }

        }
    }

    function GetCrumb(id)
    {
        for (let i = 0; i < treeData.length; i++) {
            if(treeData[i]["ParentId"] !== null)
                {
                    if(treeData[i]["NodeId"].toString() === id.toString())
                        {
                            $(".items").prepend(' > <a href="#" style="color:green;text-decoration:None;"\
                            onclick="populateTree(\''+treeData[i]["NodeId"].toString()+'\');">'+treeData[i]["NodeTitle"].toString()+'</a>');
                            return GetCrumb(treeData[i]["ParentId"]);
                        }
                }
            else
                {
                    if(treeData[i]["NodeId"].toString() === id.toString())
                        { $(".items").prepend(' <a href="#" style="color:green;text-decoration:None;"\
                        onclick="populateTree(\''+treeData[i]["NodeId"].toString()+'\');">'+treeData[i]["NodeTitle"].toString()+'</a>');
                        }
                }
        }
    }

    // selecting all the child nodes when parent is selected
    function childTicked(id){
        for(let i=0;i<treeData.length; i++){
            if(treeData[i]['ParentId'] !== null){
                if(treeData[i]["NodeId"].toString() === id.toString()){
                    if(!treeData[i].checked){
                        treeData[i].checked = true;
                        uniqueArray.push(treeData[i]['NodeId']);
                        parentTicked(treeData[i]['NodeId']); // calling parent for selecting parent nodes
                        for(let j=0; j<treeData.length; j++){
                            if(treeData[j]['ParentId'] != null){
                                if(treeData[i]["NodeId"].toString() === treeData[j]["ParentId"].toString()){
                                    childTicked(treeData[j]["NodeId"]);
                                    uniqueArray.push(treeData[j]['NodeId']);
                                }
                            }
                        }
                    }
                }
            }
            else{
                if(treeData[i]["NodeId"].toString() === id.toString()){
                    // console.log(id.id + " checked");
                    if(!treeData[i].checked){
                        treeData[i].checked = true;
                        // console.log(treeData);
                        uniqueArray.push(treeData[i]["NodeId"]);                        
                        parentTicked(treeData[i]['NodeId']);
                        for(var j=0; j<treeData.length; j++){
                            if(treeData[j]["ParentId"] != null){
                                if(treeData[i]["NodeId"].toString() === treeData[j]["ParentId"].toString()){
                                    childTicked(treeData[j]["NodeId"]);
                                    uniqueArray.push(treeData[j]['NodeId']);
                                }
                            }
                        }
                    }
                }
            }
        }
        jsonObject = uniqueArray.map(JSON.stringify);
        uniqueSet = new Set(jsonObject);
        uniqueArray = Array.from(uniqueSet).map(JSON.parse);
        console.log(uniqueArray)
        console.log(uniqueArray.length)
    }

    // uncheck function for removing all child nodes once parent is selected
    function childUnticked(id){
        for(var i=0; i<treeData.length; i++){
            if(treeData[i]["ParentId"] != null){
                if(treeData[i]["NodeId"].toString() === id.toString()){
                    const filteredArray = uniqueArray.filter(item => item != id);
                    uniqueArray = filteredArray;
                    delete treeData[i].checked;
                    // console.log(treeData[i]);
                    //parentUnticked(treeData[i]['NodeId']);
                    for(var j=0; j<treeData.length; j++){
                        if(treeData[j]["ParentId"] != null){
                            if(treeData[i]["NodeId"].toString() === treeData[j]["ParentId"].toString()){
                                const filteredArray = uniqueArray.filter(item => item != id);
                                uniqueArray = filteredArray;
                                childUnticked(treeData[j]["NodeId"]);
                            }
                        }
                    }
                }
            }
            else{
                if(treeData[i]["NodeId"].toString() === id.toString()){
                    const filteredArray = uniqueArray.filter(item => item != id);
                    uniqueArray = filteredArray;
                    delete treeData[i].checked;
                    for(var j=0; j<treeData.length; j++){
                        if(treeData[j]["ParentId"] != null){
                            if(treeData[i]["NodeId"].toString() === treeData[j]["ParentId"].toString()){
                                const filteredArray = uniqueArray.filter(item => item != id);
                                uniqueArray = filteredArray;
                                childUnticked(treeData[j]["NodeId"]);
                            }
                        }
                    }
                }
            }
        }
    console.log(uniqueArray);
    console.log("after uncheck length is " + uniqueArray.length);
    }

    // auto selecting the parent checkboxes when children checkbox is selected
    function parentTicked(id){
        for (let i = 0; i < treeData.length; i++) {
            if(treeData[i]["ParentId"] !== null){
                if(treeData[i]["NodeId"].toString() === id.toString()){
                    for(let j=0;j<treeData.length;j++){
                        if(treeData[j]["NodeId"].toString() === treeData[i]["ParentId"].toString())
                        {
                            // console.log("parentid is --->", treeData[j]["ParentId"])
                            treeData[j].checked = true;
                            parentTicked(treeData[j]["NodeId"]);
                            uniqueArray.push(treeData[j]['NodeId']);
                        }
                    }
                }
            }
        }
    }

    // will use this afterwards currently just function is created
    function parentUnticked(id){
        for (let i = 0; i < treeData.length; i++) {
            if(treeData[i]["ParentId"] !== null){
                if(treeData[i]["NodeId"].toString() === id.toString()){
                    for(let j=0;j<treeData.length;j++){
                        if(treeData[j]["NodeId"].toString() === treeData[i]["ParentId"].toString())
                        {
                            delete treeData[j].checked
                            parentUnticked(treeData[j]["NodeId"]);
                        }
                    }
                }
            }
        }
    }

    function indeterminateCall(id){
        if($(id).is(":checked")){
            childTicked(id.id);
            remainingElements();

        }
        else{
            childUnticked(id.id);
            remainingElements();
        }
    }

    function remainingElements(){
        console.log("downloading")
        if (uniqueArray.length > 0){
            document.getElementById('sort_ids').disabled = false;
        }
        else{
                document.getElementById('sort_ids').disabled = true;
        }
    }

    // function checkInternetConnection(){
    //     status = navigator.onLine;
    //     if (status) {
    //         console.log('Internet Available !!' + status);
    //     } else {
    //         console.log('No internet Available !!' + status);
    //     }  
    //     setTimeout(function() {
    //         checkInternetConnection();
    //     }, 1000);
    //   }

    $('#sort_ids').click(function(){
        //console.log("status is " + status);
        $.ajax({
            url: "/channel/downloads/",
            type: 'POST',
            data:{
                'node_values[]':  uniqueArray,
                'AppId': res,
                'AppName': AppName,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            crossDomain: true,
            datatype: "jsonp",
            beforeSend: function(){
                $('#loaded').show();
                $('#sort_ids').hide();
                //checkInternetConnection();
            },
            success: function(result){
                console.log(result);
                if(result != null && result == 'success'){
                    $('#loaded').hide();
                    $('#sort_ids').show();
                    window.location.href = '/content/app_available/';
                }
                else{
                    window.location.href = '/channel/no_internet/';
                }
            },
            error: function (error) {
                console.log('error; ' + eval(error));
            }
        });
    });



</script>
{% endblock %}

