pos/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
]

pos/channels/urls.py
from django.urls import path
from . import views


app_name = 'channels'


urlpatterns = [
    path('channel_list/', views.channel_list_on_server, name='channel_list'),
    path('return_json_value/<str:AppId>/', views.return_json_value, name='return_json_value'),
    path('show_details/<str:AppId>/<str:AppName>/', views.ShowDetailsOfChannelView.as_view(), 
        name='show_details'),
    path('downloads/', views.DownloadAndSaveView.as_view(), name='downloads'),
    path('json_data/<str:id>/', views.json_data_storage_view, name='json_data'),
    path('no_internet/', views.NoInternetView.as_view(), name='no_internet'),
]

pos/content_viewer/urls.py
from django.urls import path, re_path
from . import views

app_name = 'content_viewer'

urlpatterns = [
    path('app_available/', views.AppAvailableListView.as_view(), name='app_available'),
    path('parent_details/<str:AppId>/', views.ParentAppView.as_view(), name='parent_details'),
    path('child_details/<str:NodeId>/', views.ChildrenAppView.as_view(), name='child_details'),
    path('resource/<str:NodeId>/', views.resource_view, name='resource'),
    path('score/', views.desktop_score_data, name='score'),
    
]

pos/pos/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('register/', include('account.urls')),
    path('channel/', include('channels.urls')),
    path('content/', include('content_viewer.urls')),
    path('push/', include('push.urls')),
    path('api/', include('core_api.urls')),
    path('api/channel/', include('channels_api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/content_viewer/models.py
from django.db import models

# Create your models here.

pos/content_viewer/views.py
import os, time
import platform
from pathlib import Path
from itertools import chain
from django.http import HttpResponse
from content_viewer.extracter import extraction
from content_viewer.converter import m4v_to_mp4, wav_to_mp3
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sessions.models import Session
from core.models import DeskTopData
from channels.models import AppListFromServerData, AppAvailableInDB, FileDataToBeStored


system_os = platform.system()

# checking the list of available apps
class AppAvailableListView(ListView):
    model = AppListFromServerData
    template_name = "content_viewer/app_available.html"

    def get_queryset(self, *args, **kwargs):
        queryset = AppListFromServerData.objects.all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(AppAvailableListView, self).get_context_data(*args, **kwargs)
        queryset = self.get_queryset()
        context["apps_list"] = queryset
        # print("context is ", context)
        return context


class ParentAppView(ListView):
    # model = AppAvailableInDB
    template_name = "content_viewer/app_details.html"

    def get_queryset(self, *args, **kwargs):
        AppId = self.kwargs['AppId']
        self.request.session['AppId'] = AppId
        queryset = FileDataToBeStored.objects.all().select_related('appavailableindb').filter(appavailableindb__AppId=AppId)
        return queryset

    def get_context_data(self, *args, **kwargs):
        print("AppId is ", self.request.session.get('AppId'))
        context = super(ParentAppView, self).get_context_data(*args, **kwargs)
        queryset = self.get_queryset()
        folder_app_name = AppListFromServerData.objects.filter(AppId=self.request.session.get('AppId'))
        for app in folder_app_name:
            print(app.AppName)
            self.request.session['folder_app_name'] = app.AppName
        context['folder_app_name'] = self.request.session.get('folder_app_name')
        context["parent_details"] = queryset
        return context


class ChildrenAppView(ListView):
    template_name = "content_viewer/child_details.html"

    def get_queryset(self, *args, **kwargs):
        # global NodeId
        NodeId = self.kwargs['NodeId']
        self.request.session['NodeId'] = NodeId
        # print("child NodeId is ", self.request.session.get('NodeId'))
        queryset = FileDataToBeStored.objects.all().prefetch_related('appavailableindb').filter(appavailableindb__ParentId=NodeId)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(ChildrenAppView, self).get_context_data(*args, **kwargs)
        queryset = self.get_queryset()
        app_name = AppListFromServerData.objects.all()
        parent_db = AppAvailableInDB.objects.filter(NodeId=self.request.session.get('NodeId'))
        parent_db_title = AppAvailableInDB.objects.filter(NodeId=self.request.session.get('NodeId'))
        combined_results = ''
        chaining_queries = []
    
        while parent_db:
            parent_id = parent_db.first().ParentId
            parent_db = AppAvailableInDB.objects.filter(NodeId=parent_id)
            if not parent_db:
                pass
            else:
                parent_db = AppAvailableInDB.objects.filter(NodeId=parent_id)
                chaining_queries.append(parent_db)
        combined_results = list(chain(chaining_queries[::-1]))
        context['chaining_queries'] = combined_results
        context['app_name'] = app_name
        context['child_details'] = queryset
        context['appid'] = self.request.session.get('AppId')
        # print(context)
        context['parent_db_title'] = parent_db_title
        return context


def resource_view(request, NodeId):
    context = {}
    queryset = FileDataToBeStored.objects.filter(NodeId=NodeId)
    zip_path = os.getcwd()
    general_path = os.getcwd()
    app_name = AppListFromServerData.objects.all()
    parent_db = AppAvailableInDB.objects.filter(NodeId=NodeId)
    parent_db_title = AppAvailableInDB.objects.filter(NodeId=NodeId)
    combined_results = ''
    chaining_queries = []
        
    while parent_db:
        parent_id = parent_db.first().ParentId
        parent_db = AppAvailableInDB.objects.filter(NodeId=parent_id)
        if not parent_db:
            pass
        else:
            parent_db = AppAvailableInDB.objects.filter(NodeId=parent_id)
            chaining_queries.append(parent_db)
    
    combined_results = list(chain(chaining_queries[::-1]))
    context['chaining_queries'] = combined_results
    context['app_name'] = app_name
    context['node_id'] = NodeId
    context['appid'] = request.session.get('AppId')
    context['parent_db_title'] = parent_db_title
    # print("genral path is ", general_path, zip_path)
    if system_os == "Windows":
        zip_path = os.path.join(zip_path, r'storage'+'\\'+request.session.get('folder_app_name')+'\\'+r'content\zips')
        vid_m4v_path = os.path.join(general_path, r'storage'+'\\'+request.session.get('folder_app_name')+'\\'+r'content\videos\m4v')
        audio_wav_path = os.path.join(general_path, r'storage'+'\\'+request.session.get('folder_app_name')+'\\'+r'content\audios\wav')
    else:
        zip_path = os.path.join(zip_path, 'storage'+'/'+request.session.get('folder_app_name')+'/'+'content/zips')
        vid_m4v_path = os.path.join(general_path, 'storage/'+request.session.get('folder_app_name')+'/content/videos/m4v')
        # print("vid_m4v_path path is ", vid_m4v_path, zip_path)
        audio_wav_path = os.path.join(general_path, 'storage'+'/'+request.session.get('folder_app_name')+'/'+'content/audios/wav')
        # print("audio_wav_path path is ", audio_wav_path, zip_path)
    for qs in queryset:
        if qs.FileType == "Content" and qs.fileName.endswith('.zip'):
            zip_path1 = os.path.join(zip_path, qs.fileName)
            qs.fileName = extraction(zip_path1, request.session.get('folder_app_name'))
            zip_path = os.path.join(zip_path, qs.fileName)
            context['file'] = qs.fileName
            context['game_play'] = queryset
            return render(request, "content_viewer/content_play.html", context=context)
        elif qs.FileType == "Content" and qs.fileName.endswith('.mp4'):
            context['video_play'] = queryset
            # print(context)
            return render(request, "content_viewer/content_play.html", context=context)
        elif qs.FileType == "Content" and qs.fileName == '':
            context['no_content'] = queryset
            # print(context)
            return render(request, "content_viewer/content_play.html", context=context)
        elif qs.FileType == "Content" and qs.fileName.endswith('.m4v'):
            vid_m4v_path1 = os.path.join(vid_m4v_path, qs.fileName)
            qs.fileName = m4v_to_mp4(vid_m4v_path1, request.session.get('folder_app_name'))
            if system_os == "Windows":
                converted_video = qs.fileName.split('\\')[-1]
            else:
                converted_video = qs.fileName.split('/')[-1]
            context['m4v_video_play'] = queryset
            context['converted_video'] = converted_video
            return render(request, "content_viewer/content_play.html", context=context)
        elif qs.FileType == "Content" and qs.fileName.endswith('.mp3'):
            context['audio_play'] = queryset
            return render(request, "content_viewer/content_play.html", context=context)
        elif qs.FileType == "Content" and qs.fileName.endswith('.wav'):
            audio_wav_path1 = os.path.join(audio_wav_path, qs.fileName)
            qs.fileName = wav_to_mp3(audio_wav_path1, request.session.get('folder_app_name'))
            if system_os == "Windows":
                converted_audio = qs.fileName.split('\\')[-1]
            else:
                converted_audio = qs.fileName.split('/')[-1]
            context['wav_audio_play'] = queryset
            context['converted_audio'] = converted_audio
            return render(request, "content_viewer/content_play.html", context=context)
        elif qs.FileType == "Content" and qs.fileName.endswith('.png' or '.jpg' or '.jpeg' or '.mpeg'):
            context['wrong_format'] = queryset
            return render(request, "content_viewer/content_play.html", context=context)
        elif qs.FileType == "Content" and qs.fileName.endswith('.pdf'):
            context['pdf_play'] = queryset
            return render(request, "content_viewer/content_play.html", context=context)


def desktop_score_data(request):
    if request.method == 'GET':
        try:
            node_id = request.GET.get('NodeId')
            startTime = request.GET.get('startTime')
            endTime = request.GET.get('endTime')
            duration = request.GET.get('duration')
            user = request.user
            if user.is_authenticated:
                logged_in_user = user.username
            else:
                logged_in_user = "guest"

            # pi id data to be collected
            # passing serial_id for API 
            os.system('cat /proc/cpuinfo > serial_data.txt')
            serial_file = open('serial_data.txt', "r+")
            for line in serial_file:
                if line.startswith('Serial'):
                    serial_id = line.split(':')[1]
                    break
                else:
                    serial_id = ""

            if request.session.has_key('session_id'):
                session_id = request.session.get('session_id')

            desktop_data = DeskTopData.objects.create(session_id=session_id, node_id=node_id, start_time=startTime, 

pos/content_viewer/templates/content_viewer/app_available.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static '/css/breadcrumb.css'%}">
    <main role="main">
      {% if apps_list %}
        <ul class="breadcrumb">
          <li><a href="{% url 'content_viewer:app_available' %}">Home</a></li>
        </ul>
      {% endif %}
     
      
        <div class="album bg-light">
          <div class="container">
  
            <div class="row">
                <!-- Iterate over object_list -->
                {% for object in apps_list %}
                <div class="col-md-4 col-4">
                  <div class="card mb-4 box-shadow" >
                    <a href="{% url 'content_viewer:parent_details' AppId=object.AppId %}">
                        <img class="card-img-top" src="{% get_static_prefix %}storage/{{object.AppName}}/images/{{object.fileName}}"
                          width="50%" height="120" alt="Pratham Open School">
                    </a>
                    <div class="card-body">
                      <p class="card-text"><strong>{{ object.AppName }}</strong></p>
                      {% comment %} <p class="card-text">{{ object.AppDesc }}</p> {% endcomment %}
                      <hr>
                      <div class="d-flex justify-content-between align-items-center">
                        {% if request.user.is_authenticated %}
                        &nbsp;&nbsp;
                        <div class="btn-group">
                          <a href="{% url 'content_viewer:parent_details' AppId=object.AppId %}">
                              <button class="btn btn-outline-primary my-2 my-sm-0" type="button">View</button>
                          </a>
                          &nbsp;&nbsp;&nbsp;
                          <a href="{% url 'channels:channel_list' %}">
                              <button class="btn btn-outline-primary my-2 my-sm-0" type="button">Update</button>
                          </a>
                          {% else %}
                            <a href="{% url 'content_viewer:parent_details' AppId=object.AppId %}">
                              <button class="btn btn-outline-primary my-2 my-sm-0" type="button">View</button>
                          </a>
                            </p>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              <!-- check if empty -->
                {% empty %}
                <br>
                <br>
                <div class="row col-md-12">
                  <p class="span6" style="float: none; margin:auto;">
                  <img src='{% static "/images/error_outline-24px.svg" %}'>Content is not Available Please Download
                  </p>
                </div>
                {% if request.user.is_authenticated %}
                <div class="row col-md-12">
                  <p class="span6" style="float: none; margin:auto;">
                  <a class="btn btn-outline-success my-2 my-sm-0" type="button" href="{% url 'channels:channel_list' %}">
                    <img src='{% static "/images/get_app-24px.svg" %}'>Download</a> 
                  </p>
                </div>
                {% else %}

                <div class="row col-md-12">
                  <p class="span6" style="float: none; margin:auto;">
                  <a class="btn btn-outline-success my-2 my-sm-0" type="button" onclick="downloader()" href="{% url 'account:user_login' %}">
                    <img src='{% static "/images/get_app-24px.svg" %}'>Download</a> 
                  </p>
                </div>

                {% endif %}

              {% endfor %}
              </div>
            </div>
          </div>
  
      </main>

      <script>
          function downloader(){
            alert("you need to login to downlaod the content!")
          }
      </script>

{% endblock  %}

pos/content_viewer/templates/content_viewer/app_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/breadcrumb.css'%}">
  <main role="main">
  <ul class="breadcrumb">
    <li><a href="{% url 'content_viewer:app_available' %}">Home</a></li>
    <li>
      {% for qs in parent_details %}
        {% if qs.appavailableindb.NodeType == "App"%}
          <a href="{% url 'content_viewer:parent_details' AppId=qs.appavailableindb.AppId %}">
          {{ qs.appavailableindb.applistfromserverdata.AppName }}</a>
        {% endif %}
      {% endfor %}
    </li>
  </ul>
  
  
    <div class="album bg-light">
      <div class="container">
        <p style="font-size: 30px; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">{{ app_name }}</p>
        <div class="row">
            <!-- Iterate over object_list -->
            {% for object in parent_details %}
              {% if object.appavailableindb.ParentId == null and object.FileType == "Thumbnail" %}
          <div class="col-md-4 col-4">
            <div class="card mb-4 box-shadow" >
              <a href="{% url 'content_viewer:child_details' NodeId=object.NodeId %}">
                <img class="card-img-top" src="{% get_static_prefix %}storage/{{object.appavailableindb.applistfromserverdata.AppName}}/images/{{object.fileName}}"
                  width="50%" height="120" alt="Pratham Open School">
              </a>
              <div class="card-body">
                <p class="card-text"><strong>{{object.appavailableindb.NodeTitle}}</strong></p>
                <hr>
                <div class="d-flex justify-content-between align-items-center">
                  &nbsp;&nbsp;
                  <div class="btn-group">
                    <a href="{% url 'content_viewer:child_details' NodeId=object.NodeId %}">
                        <button class="btn btn-outline-primary " type="button">View</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endif %}
             <!-- If objet_list is empty  -->
            {% empty %}
            <p>No objects there
              <a href="{% url 'channels:channel_list' %}">
                  <button class="btn btn-outline-primary my-2 my-sm-0" type="button">Download</button>
              </a>
            </p>
          {% endfor %}
          </div>
        </div>
      </div>

  </main>
{% endblock %}

pos/content_viewer/templates/content_viewer/child_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/breadcrumb.css'%}">
<main role="main">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'content_viewer:app_available' %}">
                Home
              </a>
            </li>
            <li>
                {% for qs in app_name %}
                    <a href="{% url 'content_viewer:parent_details' AppId=qs.AppId %}">
                        {% if qs.AppId == appid %}
                            {{ qs.AppName }}
                        {% endif %}
                    </a>
                {% endfor %}
            </li>
            {% for qs in chaining_queries %}
                {% for ids in qs %}
                    <li><a href="{% url 'content_viewer:child_details' NodeId=ids.NodeId %}">
                    {{ ids.NodeTitle }}
                    </a></li>
                {% endfor %}
            {% endfor %}
            {% for qs in parent_db_title %}
                <li>{{ qs.NodeTitle }}
                </li>
            {% endfor %}
          </ul>
      </nav>
  
    <div class="album bg-light">
      <div class="container">
        <div class="row">
            <!-- Iterate over object_list -->
            {% for object in child_details %}
                {% if object.appavailableindb.NodeType == "Topic" or object.appavailableindb.NodeType == 'Language' %}
                    <div class="col-md-4 col-4">
                        <div class="card mb-4 box-shadow" style="width: 80%;">
                            <a href="{% url 'content_viewer:child_details' NodeId=object.NodeId %}">
                                <img class="card-img-top" src="{% get_static_prefix %}storage/{{object.appavailableindb.applistfromserverdata.AppName}}/images/{{object.fileName}}"
                                width="50%" height="120" alt="Pratham Open School">
                            </a>
                        <div class="card-body">
                            <span class="card-text"><strong>{{object.appavailableindb.NodeTitle}}</strong></span>
                            
                            <div class="d-flex justify-content-between align-items-center">
                                &nbsp;&nbsp;
                            <div class="btn-group">
                                <a href="{% url 'content_viewer:child_details' NodeId=object.NodeId %}">
                                    <button class="btn btn-outline-primary" type="button">View</button>
                                </a>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    {% elif object.FileType == "Thumbnail" and object.appavailableindb.NodeType == "Resource" %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow" style="width: 14rem;">
                            <a href="{% url 'content_viewer:resource' NodeId=object.NodeId %}">
                                <img class="card-img-top" src="{% get_static_prefix %}storage/{{object.appavailableindb.applistfromserverdata.AppName}}/images/{{object.fileName}}"
                                width="50%" height="120" alt="Pratham Open School">
                            </a>
                        <div class="card-body">
                            <span class="card-text"><strong>{{object.appavailableindb.NodeTitle}}</strong></span>
                            <hr>
                            <div class="d-flex justify-content-between align-items-center">
                                &nbsp;&nbsp;
                            <div class="btn-group">
                                <a href="{% url 'content_viewer:resource' NodeId=object.NodeId %}">
                                    <button class="btn btn-outline-primary my-2 my-sm-0" type="button">Watch</button>
                                </a>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                  {% endif %}
             <!-- If objet_list is empty  -->
            {% empty %}
            <p>No Data here<br>
              <a href="{% url 'channels:channel_list' %}">
                  <button class="btn btn-outline-primary my-2 my-sm-0" type="button">Download</button>
              </a>
            </p>
          {% endfor %}
          </div>
        </div>
      </div>

  </main>

{% endblock %}