pos/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
]

pos/content_viewer/urls.py
from django.urls import path, re_path
from . import views

app_name = 'content_viewer'

urlpatterns = [
    path('app_available/', views.AppAvailableListView.as_view(), name='app_available'),
    path('parent_details/<str:AppId>/', views.ParentAppView.as_view(), name='parent_details'),
    path('child_details/<str:NodeId>/', views.ChildrenAppView.as_view(), name='child_details'),
    path('resource/<str:NodeId>/', views.resource_view, name='resource'),
    path('score/', views.desktop_score_data, name='score'),
    
]

pos/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('programs/', views.program_call, name='programs'),
    path('states/', views.state_call, name='states'),
    path('districts/', views.district_call, name='districts'),
    path('blocks/', views.block_call, name='blocks'),
    path('villages/', views.show_villages, name='villages'),
    path('post_all_data/', views.post_all_data, name='post_all_data'),
    path('users/', views.user_register, name='users'),
]

pos/pos/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('register/', include('account.urls')),
    path('channel/', include('channels.urls')),
    path('content/', include('content_viewer.urls')),
    path('push/', include('push.urls')),
    path('api/', include('core_api.urls')),
    path('api/channel/', include('channels_api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/push/urls.py
from django.urls import path
from . import views

app_name = 'push'

urlpatterns = [
    path('', views.push_data, name="push-data"),
    path('usage/', views.push_usageData, name="usage"),
    path('backup/', views.backup, name="backup"),
    path('clear/', views.clear_data, name="clear"),
    path('desktop/', views.desktop_data_to_server, name="desktop"),
]

pos/templates/snippets/base_css.html
<style type="text/css">
    body{
        background-color: #fff;
    }
</style>

pos/templates/snippets/footer.html
{% load static %}
<link rel="stylesheet" href="{% static '/css/jumbotron.css'%}">
<style type="text/css">
    .footer{
        min-height: 35px;
    }
    
</style>
<hr>
<div class="d-flex flex-row align-items-center footer">
    <p class="m-auto display-5 font-weight-normal">
        Pratham Open School
    </p>
</div>

<script src="{% static '/bootstrap4/js/bootstrap.min.js'%}"></script>

pos/templates/snippets/header.html
{% load static %}
<!-- <link rel="stylesheet" href="{% static '/css/jumbotron.css'%}"> -->
<!-- <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script> -->
<style type="text/css">
    @media (min-width: 768px) {
  html {
    font-size: 16px;
  }
}
.border-top { border-top: 1px solid #e5e5e5; }
.border-bottom { border-bottom: 1px solid #e5e5e5; }

.box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .5); }
</style>

<nav class="navbar navbar-expand-md navbar-default fixed-top navbar-dark bg-dark border-bottom ">
      <a class="navbar-brand" href="#">
          <img src="{% static '/images/logop1.png' %}" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if request.user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:programs' %}">
                <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">
                    Data Download<span class="sr-only">(current)</span>
                </button>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'content_viewer:app_available' %}">
                <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Content Download</button>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'push:push-data' %}">
                <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Push Data</button>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav my-2 my-md-0 mr-md-3">
          <li class="nav-item active">
            <span style="color: #e5e5e5;">
              Welcome, {{ request.user.username }}
            </span>
          </li>
      </ul>
        <ul class="navbar-nav my-2 my-md-0 mr-md-3">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'account:user_logout' %}">
                  <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Logout</button>
              </a>
            </li>
        </ul>
      </div>
      {% else %}
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav my-2 my-md-0 mr-md-3">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'account:user_login' %}">
                    <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Login</button>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'content_viewer:app_available' %}">
                    <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Contents</button>
                </a>
            </li>
          </ul>
        </div>
      {% endif %}
    </nav>
    <!-- <hr> -->
   