pos/pos/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('register/', include('account.urls')),
    path('channel/', include('channels.urls')),
    path('content/', include('content_viewer.urls')),
    path('push/', include('push.urls')),
    path('api/', include('core_api.urls')),
    path('api/channel/', include('channels_api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/push/urls.py
from django.urls import path
from . import views

app_name = 'push'

urlpatterns = [
    path('', views.push_data, name="push-data"),
    path('usage/', views.push_usageData, name="usage"),
    path('backup/', views.backup, name="backup"),
    path('clear/', views.clear_data, name="clear"),
    path('desktop/', views.desktop_data_to_server, name="desktop"),
]

pos/push/models.py
from django.db import models

# Create your models here.

pos/push/views.py
import os
import json
import string
import random
import platform
import datetime
import requests
import time
from pathlib import Path
from django.contrib import messages
from core.models import UsageData, DeskTopData
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.contrib.sessions.models import Session


system_os = platform.system()
print(system_os)
print(type(system_os))

headers = {
    'cache-control': "no-cache",
    'content-type': "application/json",
    'Accept': 'application/json'
}


def push_data(request):
    return render(request, 'push/data_to_push.html')


def create_usage_directory():
    # global homeDir
    print("usgd")
    if system_os == 'Windows':
        print("usgdata")
        homeDir = str(Path.home())
        homeDir = os.path.join(homeDir, r"generate\Backup")
        usageDir = os.path.join(homeDir, r"usageData")
        print(usageDir)
        if not os.path.exists(usageDir):
            os.makedirs(usageDir)
        else:
            pass
    else:
        print("linux")
        homeDir = str(Path.home())
        homeDir = os.path.join(homeDir, "generate/Backup")
        usageDir = os.path.join(homeDir, "usageData")
        if not os.path.exists(usageDir):
            os.makedirs(usageDir)
        else:
            pass

    # print("homeDir is from create_dir ", homeDir)
    return usageDir


def create_desktop_directory():
    # global homeDir
    if system_os == 'Windows':
        try:
            print(system_os, "deskt")
            homeDir = str(Path.home())
            homeDir = os.path.join(homeDir, r"generate\Backup")
            desktopDir = os.path.join(homeDir, r"desktopData")
            print(desktopDir)
            if not os.path.exists(desktopDir):
                os.makedirs(desktopDir)
            else:
                pass
        except Exception as dir_err:
            print(dir_err)
    else:
        homeDir = str(Path.home())
        homeDir = os.path.join(homeDir, "generate/Backup")
        desktopDir = os.path.join(homeDir, "desktopData")
        if not os.path.exists(desktopDir):
            os.makedirs(desktopDir)
        else:
            pass

    # print("homeDir is from create_dir ", homeDir)
    return desktopDir


def push_usageData(request):
    i = 1
    n = 6
    serial_line = ''
    randstr = ''.join(random.choice(
        string.ascii_uppercase + string.digits) for _ in range(n))

    while True:
        fetch_url = "http://192.168.4.1:8000/api/usagedata/?table_name=USAGEDATA&page=%s&page_size=15" % i

        # post api
        post_url = "http://rpi.prathamskills.org/api/KolibriSession/Post"

        response = requests.get(fetch_url)

        lstscore = json.loads(response.content.decode('utf-8'))
        print("lstscore ", lstscore['count'])

        # pi id data to be collected
        os.system('cat /proc/cpuinfo > serial_data.txt')
        serial_file = open('serial_data.txt', "r+")
        for line in serial_file:
            if line.startswith('Serial'):
                serial_line = line

        lstscore['serial_id'] = serial_line

        # checks the value of count
        if lstscore['count'] == 0 and lstscore['next'] is None:
            print("no data")
            return render(request, 'push/data_to_push.html')
        elif lstscore['count'] != 0 and lstscore['next'] is None:
            try:
                data = lstscore
                response_post = requests.post(
                    post_url,
                    headers=headers,
                    data=json.dumps(data),
                )

                # print("elif", response_post.status_code, response_post.reason)
            except Exception as bkp_error_next:
                print("bkp error is ", bkp_error_next)
            return render(request, 'push/data_to_push.html')
        else:
            data = lstscore  # providing lstscore value to data variable
            try:
                response_post = requests.post(
                    post_url,
                    headers=headers,
                    data=json.dumps(data),
                )

                # print("el", response_post.status_code, response_post.reason)

            except Exception as e1:
                print("error e1 is ", e1)
                return False
        i = i+1
    return render(request, 'push/data_to_push.html')


def backup(request):
    i = 1
    n = 6
    serial_line = ''
    randstr = ''.join(random.choice(
        string.ascii_uppercase + string.digits) for _ in range(n))

    while True:
        # usagedata backup code
        # get api
        usage_url = "http://192.168.4.1:8000/api/usagedata/?table_name=USAGEDATA&page=%s&page_size=15" % i
        print("usage_url ", usage_url)

        response = requests.get(usage_url)

        lstscore = json.loads(response.content.decode('utf-8'))

        print(response.status_code)
        if response.status_code == 404:
            return render(request, 'push/data_to_push.html')

        # pi id data to be collected
        os.system('cat /proc/cpuinfo > serial_data.txt')
        serial_file = open('serial_data.txt', "r+")
        for line in serial_file:
            if line.startswith('Serial'):
                serial_line = line

        lstscore['serial_id'] = serial_line

        if lstscore['count'] == 0 and lstscore['next'] is None:
            print("no data")
            return render(request, 'push/data_to_push.html')
        elif lstscore['count'] != 0 and lstscore['next'] is None:
            try:
                with open(os.path.join(create_usage_directory(),
                                       randstr + str(datetime.datetime.now()) + '.json'),
                          "w") as outfile:
                    json.dump(lstscore, outfile, indent=4, sort_keys=True)
            except Exception as bkp_error_next:
                print("bkp error is ", bkp_error_next)
                return render(request, 'push/data_to_push.html')
        else:
            print("lstscore ", lstscore['next'])
            try:
                with open(os.path.join(create_usage_directory(),
                                       randstr + str(datetime.datetime.now()) + '.json'),
                          "w") as outfile:
                    json.dump(lstscore, outfile, indent=4, sort_keys=True)
            except Exception as bkp_error:
                print("bkp error is ", bkp_error)
                return render(request, 'push/data_to_push.html')

        # desktop data backup
        desktop_url = "http://192.168.4.1:8000/api/desktopdata/?page=%s&page_size=15" % i
        appList_url = "http://192.168.4.1:8000/api/channel/AppList/"

        # desktop data url
        desktop_response = requests.get(desktop_url, headers=headers)
        desktop_result = json.loads(desktop_response.content.decode('utf-8'))

        # app list url
        appList_response = requests.get(appList_url, headers=headers)
        appList_result = json.loads(appList_response.content.decode('utf-8'))

        if desktop_response.status_code == 404 and appList_response.status_code == 404:
            return render(request, 'push/data_to_push.html')
        elif desktop_response.status_code == 404:
            return render(request, 'push/data_to_push.html')
        else:
            pass

        if desktop_result['count'] == 0 and desktop_result['next'] is None:
            # print("no data")
            return render(request, 'push/data_to_push.html')
        elif desktop_result['count'] != 0 and desktop_result['next'] is None:
            try:
                desktop_data_to_post = {
                    "desktop_result": desktop_result,
                    "appList_result": appList_result,
                }
                try:
                    with open(os.path.join(create_desktop_directory(),
                                        randstr + str(datetime.datetime.now()) + '.json'),
                            "w") as outfile:
                        json.dump(desktop_data_to_post, outfile, indent=4, sort_keys=True)
                except Exception as bkp_error_next:
                    print("bkp error is ", bkp_error_next)
                    return render(request, 'push/data_to_push.html')

            except Exception as e:
                # return False
                return render(request, 'push/data_to_push.html')
        else:
            try:
                desktop_data_to_post = {
                    "desktop_result": desktop_result,
                    "appList_result": appList_result,
                }
                try:
                    with open(os.path.join(create_desktop_directory(),
                                        randstr + str(datetime.datetime.now()) + '.json'),
                            "w") as outfile:
                        json.dump(desktop_data_to_post, outfile, indent=4, sort_keys=True)
                except Exception as bkp_error_next:
                    print("bkp error is ", bkp_error_next)
                    return render(request, 'push/data_to_push.html')

            except Exception as e:
                print("dtp post error ", e)
                return False
            # return render(request, 'push/data_to_push.html')


        i = i+1

    return render(request, 'push/data_to_push.html')


def clear_data(request):
    instance_usage = UsageData.objects.all()
    instance_usage.delete()
    instance_desktop = DeskTopData.objects.all()
    instance_desktop.delete()
    return render(request, 'push/data_to_push.html')


def desktop_data_to_server(request):
    i = 1
    n = 6
    serial_line = ''
    randstr = ''.join(random.choice(
        string.ascii_uppercase + string.digits) for _ in range(n))

    if request.session.has_key('session_id'):
        sessionId = request.session.get('session_id')

    while True:
        # get api
        desktop_url = "http://192.168.4.1:8000/api/desktopdata/?page=%s&page_size=15" % i

pos/push/templates/push/data_to_push.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style type="text/css">
        .success{
            list-style: none;
            background-color: #26eda4;
            color: white;
            box-shadow: 12px 12px 12px #e61c66;
            text-align: center;
        }
    </style>
    <br>
    <br>
    <!-- {% url 'push:usage' %} -->
      <div class="row col-md-12">
        <p class="span6" style="float: none; margin:auto;">
        <a class="btn btn-warning my-2 my-sm-0" id="usage" name="push" type="button"
         href="{% url 'push:usage' %}">
            Upload To Server &#8593</a> 
        </p>
        <p class="span6" style="float: none; margin:auto;">
            <a class="btn btn-warning my-2 my-sm-0" id="backup" type="button" href="{% url 'push:backup' %}">
                Backup Data
            </a> 
            </p>
            <p class="span6" style="float: none; margin:auto;">
                <a class="btn btn-warning my-2 my-sm-0" id="clear" type="button" href="{% url 'push:clear' %}">
                Delete Data</a> 
            </p>
            <p class="span6" style="float: none; margin:auto;">
                <a class="btn btn-warning my-2 my-sm-0" id="desktop" type="button" href="{% url 'push:desktop' %}">DeskTop Data</a> 
            </p>
      </div>
      <!-- The Modal -->
      <div class="container modal text-center" id="popup">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Data Push</h4>
              <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
            </div>

            <!-- Modal body -->
            <div class="modal-body" id="pushdetails">
                <div class="loading" id="loaded" style="display:none;">
                    <div class="loader">
                    </div>
                    <button class="btn btn-primary" disabled>
                                <span class="spinner-grow spinner-grow-sm"></span>
                                Please wait while data is uploading!!
                        </button>
                </div>

            </div>

          </div>
        </div>
      </div>

      <!-- The Modal -->
      <div class="container modal text-center" id="popupBkp">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Data Backup</h4>
              <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
            </div>

            <!-- Modal body -->
            <div class="modal-body" id="pushdetailsBkp">
                <div class="loading" id="loadedBkp" style="display:none;">
                    <div class="loader">
                    </div>
                    <button class="btn btn-primary" disabled>
                                <span class="spinner-grow spinner-grow-sm"></span>
                                Please wait while we take backup of your data!!
                        </button>
                </div>

            </div>

          </div>
        </div>
      </div>

    <!-- The Modal -->
      <div class="container modal text-center" id="cleardata">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Data clear</h4>
              <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
            </div>

            <!-- Modal body -->
            <div class="modal-body" id="pushdetailsclear">
                <div class="loading" id="loadedclear" style="display:none;">
                    <div class="loader">
                    </div>
                    <button class="btn btn-primary" disabled>
                                <span class="spinner-grow spinner-grow-sm"></span>
                                Please wait while we delete the data!!
                        </button>
                </div>

            </div>

          </div>
        </div>
      </div>

      <!-- The Modal -->
      <div class="container modal text-center" id="desktopdata">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">DesktopData Push</h4>
              <!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
            </div>

            <!-- Modal body -->
            <div class="modal-body" id="pushdesktop">
                <div class="loading" id="loadedesktop" style="display:none;">
                    <div class="loader">
                    </div>
                    <button class="btn btn-primary" disabled>
                                <span class="spinner-grow spinner-grow-sm"></span>
                                Please wait while we Push the desktop data!!
                        </button>
                </div>

            </div>

          </div>
        </div>
      </div>

    <script>
        
        $('#usage').click(function () {
                $.ajax({
                    type: 'POST',
                    crossDomain: true,
                    dataType: "jsonp",
                    beforeSend: function(){
                        $('#popup').show();
                        $('#loaded').show();
                    },
                    success: function(){
                        $('#popup').hide();
                        $('#loaded').hide();
                    },
                    error: function (error) {
                        console.log('error; ' + eval(error));
                    }
                });
            });
        
        $('#backup').click(function () {
                $.ajax({
                    type: 'POST',
                    crossDomain: true,
                    dataType: "jsonp",
                    beforeSend: function(){
                        $('#popupBkp').show();
                        $('#loadedBkp').show();
                    },
                    success: function(){
                        $('#popupBkp').hide();
                        $('#loadedBkp').hide();
                    },
                    error: function (error) {
                        console.log('error; ' + eval(error));
                    }
                });
            });
        $('#clear').click(function () {
                $.ajax({
                    type: 'POST',
                    crossDomain: true,
                    dataType: "jsonp",
                    beforeSend: function(){
                        $('#cleardata').show();
                        $('#loadedclear').show();
                    },
                    success: function(){
                        $('#cleardata').hide();
                        $('#loadedclear').hide();
                    },
                    error: function (error) {
                        console.log('error; ' + eval(error));
                    }
                });
            });
            $('#desktop').click(function () {
                $.ajax({
                    type: 'POST',
                    crossDomain: true,
                    dataType: "jsonp",
                    beforeSend: function(){
                        $('#desktopdata').show();
                        $('#loadedesktop').show();
                    },
                    success: function(){
                        $('#desktopdata').hide();
                        $('#loadedesktop').hide();
                    },
                    error: function (error) {
                        console.log('error; ' + eval(error));
                    }
                });
            });

    </script>

{% endblock %}